/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package grupo10_tp6;

import java.util.HashSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ezequiel
 */
public class ConsultaPorRubro extends javax.swing.JInternalFrame {
    DefaultTableModel model = new DefaultTableModel(){
        public boolean isCellEditable (int f, int c){
        return false;
    }
    };
    /**
     * Creates new form ConsultaPorNombre
     */
    public ConsultaPorRubro() {
        initComponents();
        armarCabecera();
        llenarTabla();
        cargarCbRubro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        labelRubro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRubro = new javax.swing.JTable();
        jcbRubro = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setTitle("DeTodo S.A. | Consulta por Rubro");

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelTitulo.setText("Listado por Rubro");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        labelRubro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelRubro.setText("Rubro:");

        jTableRubro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Precio", "Categoria", "Stock"
            }
        ));
        jScrollPane1.setViewportView(jTableRubro);

        jcbRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbRubroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelRubro)
                                .addGap(18, 18, 18)
                                .addComponent(jcbRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTitulo)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelRubro)
                            .addComponent(jcbRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jcbRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbRubroActionPerformed
        // TODO add your handling code here:
        selectRubro();
    }//GEN-LAST:event_jcbRubroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRubro;
    private javax.swing.JComboBox<String> jcbRubro;
    private javax.swing.JLabel labelRubro;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables

    
    
    public void selectRubro(){
        borrarFilas();
        String filtro = jcbRubro.getSelectedItem().toString();
        System.out.println(filtro);
        // convierto el String del combo a Categoria
        Categoria categoriaFiltro;
        categoriaFiltro = ProductoManager.devuelveCategoria(filtro);

        for (Producto p : MainFrame.listaProductos) {
            // solo agrego los productos que coincidan con la categoría seleccionada
            if (p.getRubro() == categoriaFiltro) {
                model.addRow(new Object[]{
                    p.getCodigo(),
                    p.getDescripcion(),
                    p.getPrecio(),
                    p.getRubro(),
                    p.getStock()
                });
            }
        }
    }
    
// -------------------------------- Armado de Tabla --------------------------------
    
    public void cargarCbRubro() {
        HashSet<String> lista = new HashSet<>();
        for (Producto producto : MainFrame.listaProductos ) {
            String x = producto.getRubroAsString();
            lista.add(x);
        }
        for (String A : lista) {
            jcbRubro.addItem(A);
        }
    }
    
// -------------------------------- Armado de Tabla --------------------------------
    public void armarCabecera(){
        model = new javax.swing.table.DefaultTableModel();
        model.addColumn("Codigo");
        model.addColumn("Descripción");
        model.addColumn("Precio");
        model.addColumn("Stock");
        model.addColumn("Rubro");
        jTableRubro.setModel(model);
    }
    
    public void borrarFilas(){
        model.setRowCount(0);
    }

    public void llenarTabla(){
        borrarFilas();
        for (Producto p : MainFrame.listaProductos) {
            
            model.addRow(new Object[]{
                p.getCodigo(),
                p.getDescripcion(),
                p.getPrecio(),
                p.getRubro(),
                p.getStock(),
            });
            
            System.out.println("------");
            System.out.println(p.getCodigo());
            System.out.println(p.getDescripcion());
            System.out.println(p.getPrecio());
            System.out.println(p.getRubro());
            System.out.println(p.getStock());
            System.out.println("------");
        }
    }
}
