/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grupo10_tp6;

import img.ImagenFondo;
import java.util.TreeSet;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 * @author Grupo10 TP6 Altamirano Karina Gianfranco Antonacci Matías Bequis
 * Marcos Ezequiel Dave Natalia Quiroga Dorzan Alejo Franzinni Tatiana
 */
public class MainFrame extends javax.swing.JFrame {
    public static TreeSet<Producto> listaProductos = new TreeSet<>();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        inicializarProductosEjemplo();

    }
    
    private void inicializarProductosEjemplo() {
        // Solo agregar productos si la lista está vacía (para evitar duplicados)
        if (listaProductos.isEmpty()) {
            try {
                // Agregar algunos productos de ejemplo
                listaProductos.add(new Producto(1, "Arroz Gallo Oro 1kg", 1200.0, Categoria.COMESTIBLE, 50));
                listaProductos.add(new Producto(2, "Aceite Girasol Natura 900ml", 2800.0,Categoria.COMESTIBLE , 25));
                listaProductos.add(new Producto(3, "Azúcar Natura 1kg", 1500.0, Categoria.COMESTIBLE, 40));
                listaProductos.add(new Producto(11, "Detergente Ala Líquido 3L", 3500.0, Categoria.LIMPIEZA, 20));
                listaProductos.add(new Producto(12, "Lavandina Ayudín 1L", 1800.0, Categoria.LIMPIEZA, 30));
                listaProductos.add(new Producto(13, "Jabón en Polvo Skip 800g", 2200.0, Categoria.LIMPIEZA, 25));
                listaProductos.add(new Producto(28, "Cepillo de Dientes Oral-B", 1800.0, Categoria.PERFUMERIA, 22));
                listaProductos.add(new Producto(29, "Enjuague Bucal Oral-B", 2950.0, Categoria.PERFUMERIA, 12));
                listaProductos.add(new Producto(30, "Máquina de Afeitar Gillette", 4200.0, Categoria.PERFUMERIA, 10));
                
                System.out.println("Productos de ejemplo cargados: " + listaProductos.size() + " productos");
            } catch (Exception e) {
                System.err.println("Error al cargar productos de ejemplo: " + e.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new img.ImagenFondo();
        barra_menu = new javax.swing.JMenuBar();
        jm_administracion = new javax.swing.JMenu();
        jm_GestionDeProductos = new javax.swing.JMenuItem();
        jm_consultas = new javax.swing.JMenu();
        jm_ConsultaPorNombre = new javax.swing.JMenuItem();
        jm_ConsultaPorPrecio = new javax.swing.JMenuItem();
        jm_ConsultaPorRubro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TP6 DeTodo S.A.");
        setPreferredSize(new java.awt.Dimension(1200, 700));

        Escritorio.setPreferredSize(new java.awt.Dimension(1200, 700));

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1145, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
        );

        jm_administracion.setText("Administración");

        jm_GestionDeProductos.setText("Gestión de productos");
        jm_GestionDeProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_GestionDeProductosActionPerformed(evt);
            }
        });
        jm_administracion.add(jm_GestionDeProductos);

        barra_menu.add(jm_administracion);

        jm_consultas.setText("Consultas");

        jm_ConsultaPorNombre.setText("Consulta por Nombre");
        jm_ConsultaPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_ConsultaPorNombreActionPerformed(evt);
            }
        });
        jm_consultas.add(jm_ConsultaPorNombre);

        jm_ConsultaPorPrecio.setText("Consulta por Precio");
        jm_ConsultaPorPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_ConsultaPorPrecioActionPerformed(evt);
            }
        });
        jm_consultas.add(jm_ConsultaPorPrecio);

        jm_ConsultaPorRubro.setText("Consulta por Rubro");
        jm_ConsultaPorRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_ConsultaPorRubroActionPerformed(evt);
            }
        });
        jm_consultas.add(jm_ConsultaPorRubro);

        barra_menu.add(jm_consultas);

        setJMenuBar(barra_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1145, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // -------------------------------- Consulta por Precio --------------------------------
    private void jm_ConsultaPorPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_ConsultaPorPrecioActionPerformed
        ConsultaPorPrecio ventana = null;

        // Buscar si ya existe una instancia en el escritorio
        for (JInternalFrame frame : Escritorio.getAllFrames()) {
            if (frame instanceof ConsultaPorPrecio) {
                ventana = (ConsultaPorPrecio) frame;
                break;
            }
        }

        if (ventana == null) {
            // Crear nueva si no estaba abierta la ventana
            ventana = new ConsultaPorPrecio();
            // Instanciarla
            Escritorio.add(ventana);

            // Centrar
            int x = (Escritorio.getWidth() - ventana.getWidth()) / 2;
            int y = (Escritorio.getHeight() - ventana.getHeight()) / 2;
            ventana.setLocation(x, y);

            ventana.setVisible(true);
        } else {
            // Si ya estaba, traerla al frente
            try {
                ventana.setIcon(false); // restaurar si estaba minimizada
                ventana.setSelected(true);
                ventana.toFront();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jm_ConsultaPorPrecioActionPerformed

    // -------------------------------- Gestion de productos --------------------------------
    private void jm_GestionDeProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_GestionDeProductosActionPerformed
        GestionDeProductos ventana = null;

        // Buscar si ya existe una instancia en el escritorio
        for (JInternalFrame frame : Escritorio.getAllFrames()) {
            if (frame instanceof GestionDeProductos) {
                ventana = (GestionDeProductos) frame;
                break;
            }
        }

        if (ventana == null) {
            // Crear nueva si no estaba abierta la ventana
            ventana = new GestionDeProductos();
            // Instanciarla
            Escritorio.add(ventana);

            // Centrar
            int x = (Escritorio.getWidth() - ventana.getWidth()) / 2;
            int y = (Escritorio.getHeight() - ventana.getHeight()) / 2;
            ventana.setLocation(x, y);

            ventana.setVisible(true);
        } else {
            // Si ya estaba, traerla al frente
            try {
                ventana.setIcon(false); // restaurar si estaba minimizada
                ventana.setSelected(true);
                ventana.toFront();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jm_GestionDeProductosActionPerformed

    // -------------------------------- Consulta por Nombre --------------------------------
    private void jm_ConsultaPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_ConsultaPorNombreActionPerformed
        ConsultaPorNombre ventana = null;

        // Buscar si ya existe una instancia en el escritorio
        for (JInternalFrame frame : Escritorio.getAllFrames()) {
            if (frame instanceof ConsultaPorNombre) {
                ventana = (ConsultaPorNombre) frame;
                break;
            }
        }

        if (ventana == null) {
            // Crear nueva si no estaba abierta la ventana
            ventana = new ConsultaPorNombre();
            // Instanciarla
            Escritorio.add(ventana);

            // Centrar
            int x = (Escritorio.getWidth() - ventana.getWidth()) / 2;
            int y = (Escritorio.getHeight() - ventana.getHeight()) / 2;
            ventana.setLocation(x, y);

            ventana.setVisible(true);
        } else {
            // Si ya estaba, traerla al frente
            try {
                ventana.setIcon(false); // restaurar si estaba minimizada
                ventana.setSelected(true);
                ventana.toFront();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jm_ConsultaPorNombreActionPerformed

    // -------------------------------- Consulta por Rubro --------------------------------
    private void jm_ConsultaPorRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_ConsultaPorRubroActionPerformed
        ConsultaPorRubro ventana = null;

        // Buscar si ya existe una instancia en el escritorio
        for (JInternalFrame frame : Escritorio.getAllFrames()) {
            if (frame instanceof ConsultaPorRubro) {
                ventana = (ConsultaPorRubro) frame;
                break;
            }
        }

        if (ventana == null) {
            // Crear nueva si no estaba abierta la ventana
            ventana = new ConsultaPorRubro();
            // Instanciarla
            Escritorio.add(ventana);

            // Centrar
            int x = (Escritorio.getWidth() - ventana.getWidth()) / 2;
            int y = (Escritorio.getHeight() - ventana.getHeight()) / 2;
            ventana.setLocation(x, y);

            ventana.setVisible(true);
        } else {
            // Si ya estaba, traerla al frente
            try {
                ventana.setIcon(false); // restaurar si estaba minimizada
                ventana.setSelected(true);
                ventana.toFront();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jm_ConsultaPorRubroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuBar barra_menu;
    private javax.swing.JMenuItem jm_ConsultaPorNombre;
    private javax.swing.JMenuItem jm_ConsultaPorPrecio;
    private javax.swing.JMenuItem jm_ConsultaPorRubro;
    private javax.swing.JMenuItem jm_GestionDeProductos;
    private javax.swing.JMenu jm_administracion;
    private javax.swing.JMenu jm_consultas;
    // End of variables declaration//GEN-END:variables

    

}
